### ISSUE TITLE
Event sourcing & privacy

### ISSUE THREAD

**Issue by joepio** [ontola/linked-delta#12]
Some deltas (or _events_, units of data change) might contain privacy related data, which might need to be removed when a user issues Article 17 of the GDPR: the right to be forgotten. In conventional systems, data removal can be quite trivial: just remove it. In Event Sourced / CQRS systems (which is something that this spec seems to make possible), removing data becomes tricky, because we assume immutability in our event store. We can't just add a "remove this resource" delta to the stack and remove the data from the query systems - the privacy sensitive information needs to be removed from all the deltas as well. We need to mutate the ledger to comply with GDPR.

But how do you know which deltas you need to remove? Removing all statements for a certain subject seems logical, but what if the subject had an IRI change? You'd need to find all the IRIs for the subject, and remove every statement where any version of its IRI would appear. That's not even possible in our architecture, since we use Kafka and that uses immutable events.

Of course, all the query systems would need to execute the data removal delta as well. After that happens and succeeds, the delta itself should be removed, too - because that, too, contains privacy related data.

If finding all the delta statements is too costly, we might simply remove _all of the events_, but if we do that, we lose one of the coolest features of event sourcing: to add new query systems / loaders and fill them with all the data.

Another solution is to re-create linked deltas from any of the query systems, but doing this could be costly and could remove relevant information such as revisions of content.

Another option to encrypt all user data with keys, unique to each user, and throw that key away when the user requests data removal. For Linked Data, this means that we encrypt every statement where the user's IRI appears. Seems like a decent solution, more details [here](https://blog.gemalto.com/security/2017/08/16/deeper-dive-into-gdpr-right-to-be-forgotten/). However, it also introduces complexity in key management and decryption logic. Also, the re-usability of the store is limited, since everyone will need the keys, and sharing them kind of defeats the purpose. And it does not provide an answer to when private data is stored in a public resource by accident... And of course, even the best cryptography could someday be defeated. Some quantum computer may end all private data in these encrypted stores.

So it seems like we _need_ mutability of our store to have a privacy friendly architecture. 

Thoughts?

**Comment by rescribet** [comment]
The stream can just be filtered to a new topic, but this question is general to ES in general which isn't required for using linked delta.
